export const COMPONENTS_TEST_IDS = {
  BACK_BUTTON: "SRC_COMPONENTS_BACKBUTTON",
  BADGE: "SRC_COMPONENTS_BADGE",
  SEARCH_SELECTOR: "SRC_COMPONENTS_SEARCHSELECTOR",
  SEARCH_INPUT: "SRC_COMPONENTS_SEARCHINPUT",
  SEARCH_BUTTON: "SRC_COMPONENTS_SEARCHBUTTON",
  HEADER: "SRC_COMPONENTS_HEADER",
  LOCK_BUTTON: "SRC_COMPONENTS_LOCKBUTTON",
  LOADING_SCREEN: "SRC_COMPONENTS_LOADINGSCREEN",

  EMPTY_FAVORITES: "SRC_COMPONENTS_FAVORITES_EMPTYFAVORITES",
  EMPTY_FAVORITES_ICON: "SRC_COMPONENTS_FAVORITES_EMPTYFAVORITES_ICON",

  SHOWS_LIST: "SRC_COMPONENTS_HOME_SHOWSLIST",
  FOOTER_PREVIOUS_BUTTON: "SRC_COMPONENTS_HOME_SHOWSLISTFOOTER_PREVIOUSBUTTON",
  FOOTER_NEXT_BUTTON: "SRC_COMPONENTS_HOME_SHOWSLISTFOOTER_NEXTBUTTON",
};

export const SCREEN_COMPONENTS_TEST_IDS = {
  TOP_LOGO: "SRC_APP_AUTH_TOPLOGO",
  LOGO_LETTERS: "SRC_APP_AUTH_LOGOLETTERS",
  TOUCHABLE_WITHOUT_FEEDBACK: "SRC_APP_AUTH_TOUCHABLEWITHOUTFEEDBACK",

  SPLASH_IMAGE: "SRC_APP_INDEX_SPLASHIMAGE",

  DELETE_ADD_FAVORITE_BUTTON: "SRC_APP_SHOW_DELETEADDFAVORITEBUTTON",
  SHOW_IMAGE: "SRC_APP_SHOW_SHOWIMAGE",
};
