export const COMPONENTS_TEST_IDS = {
  BACK_BUTTON: "SRC_COMPONENTS_BACKBUTTON",
  BADGE: "SRC_COMPONENTS_BADGE",
  SEARCH_SELECTOR: "SRC_COMPONENTS_SEARCHSELECTOR",
  SEARCH_INPUT: "SRC_COMPONENTS_SEARCHINPUT",
  SEARCH_BUTTON: "SRC_COMPONENTS_SEARCHBUTTON",
  HEADER: "SRC_COMPONENTS_HEADER",
  LOCK_BUTTON: "SRC_COMPONENTS_LOCKBUTTON",
};
